
# Dados fornecido
from datetime import datetime, timedelta

data_atual = datetime.now()
primeiro_dia_mes_atual = data_atual.replace(day=1)
ultimo_dia_mes_anterior = primeiro_dia_mes_atual - timedelta(days=1)
mes_anterior = ultimo_dia_mes_anterior.strftime('%m')
ano_atual = ultimo_dia_mes_anterior.strftime('%Y')
dtCliente_Atual = f"{mes_anterior} {ano_atual}"

dados = {
    'Origem': [
        rf'W:\Shared With Me\Clientes\Jettax\{dtCliente_Atual}\NFS 01\NOTAS\JETTAX\3sixty_produtora_de_eventos_e_live_mar_780841',
        rf'W:\Shared With Me\Clientes\Jettax\{dtCliente_Atual}\NFS 01\NOTAS\JETTAX\ac_yabiku_filial_780767',
        rf'W:\Shared With Me\Clientes\Jettax\{dtCliente_Atual}\NFS 01\NOTAS\JETTAX\ac_yabiku_matriz_780751',
        rf'W:\Shared With Me\Clientes\Jettax\{dtCliente_Atual}\NFS 01\NOTAS\JETTAX\acp_filial_diadema_794322',
        rf'W:\Shared With Me\Clientes\Jettax\{dtCliente_Atual}\NFS 01\NOTAS\JETTAX\acp_matriz_794320',
        rf'W:\Shared With Me\Clientes\Jettax\{dtCliente_Atual}\NFS 01\NOTAS\JETTAX\adachi_consultoria_923904',
        rf'W:\Shared With Me\Clientes\Jettax\{dtCliente_Atual}\NFS 01\NOTAS\JETTAX\agile_com_varej_de_prod_eletromedicos_780810',
        rf'W:\Shared With Me\Clientes\Jettax\{dtCliente_Atual}\NFS 01\NOTAS\JETTAX\aguaplus_pocos_artesianos_-_eireli_794324',
        rf'W:\Shared With Me\Clientes\Jettax\{dtCliente_Atual}\NFS 01\NOTAS\JETTAX\aguaplus_saneamento_e_processos_ltda_794325',
        rf'W:\Shared With Me\Clientes\Jettax\{dtCliente_Atual}\NFS 01\NOTAS\JETTAX\andrea_oki_engenharia_ltda_780824',
        rf'W:\Shared With Me\Clientes\Jettax\{dtCliente_Atual}\NFS 01\NOTAS\JETTAX\auto_moto_escola_netuno_780843',
        rf'W:\Shared With Me\Clientes\Jettax\{dtCliente_Atual}\NFS 01\NOTAS\JETTAX\barao_esquadrias_de_madeiras_ltda_780757',
        rf'W:\Shared With Me\Clientes\Jettax\{dtCliente_Atual}\NFS 01\NOTAS\JETTAX\bdm_micromercados_ltda_780823',
        rf'W:\Shared With Me\Clientes\Jettax\{dtCliente_Atual}\NFS 01\NOTAS\JETTAX\bruno_diogo_andre_desenvolvedor_794333',
        rf'W:\Shared With Me\Clientes\Jettax\{dtCliente_Atual}\NFS 01\NOTAS\JETTAX\caio_m.m.azeredo_socied.indiv._advoc_794334',
        rf'W:\Shared With Me\Clientes\Jettax\{dtCliente_Atual}\NFS 01\NOTAS\JETTAX\cecere_administradora_de_bens_ltda_780826',
        rf'W:\Shared With Me\Clientes\Jettax\{dtCliente_Atual}\NFS 01\NOTAS\JETTAX\citini_representao_comercial_ltda_1092149',
        rf'W:\Shared With Me\Clientes\Jettax\{dtCliente_Atual}\NFS 01\NOTAS\JETTAX\clinica_valentim_780829',
        rf'W:\Shared With Me\Clientes\Jettax\{dtCliente_Atual}\NFS 01\NOTAS\JETTAX\clinica_veterinaria_nosso_lar_ltda_794339',
        rf'W:\Shared With Me\Clientes\Jettax\{dtCliente_Atual}\NFS 01\NOTAS\JETTAX\company_s_com.design__tec._eireli_me_780766',
        rf'W:\Shared With Me\Clientes\Jettax\{dtCliente_Atual}\NFS 01\NOTAS\JETTAX\consultorio_odontologico_suguiura_ltda_780835',
        rf'W:\Shared With Me\Clientes\Jettax\{dtCliente_Atual}\NFS 01\NOTAS\JETTAX\d_goncalves_imoveis_ltda_794342',
        rf'W:\Shared With Me\Clientes\Jettax\{dtCliente_Atual}\NFS 01\NOTAS\JETTAX\dac_ss_ltda_-_me_780735',
        rf'W:\Shared With Me\Clientes\Jettax\{dtCliente_Atual}\NFS 01\NOTAS\JETTAX\davi_administracao_de_bens_imoveis_e_780831',
        rf'W:\Shared With Me\Clientes\Jettax\{dtCliente_Atual}\NFS 01\NOTAS\JETTAX\dotbuild_it_solution_tecnologia_ltda_780732',
        rf'W:\Shared With Me\Clientes\Jettax\{dtCliente_Atual}\NFS 01\NOTAS\JETTAX\dotbuild_sistemas_ltda_me_794346',
        rf'W:\Shared With Me\Clientes\Jettax\{dtCliente_Atual}\NFS 01\NOTAS\JETTAX\eco_terra_transportes_e_remocao_de_entulhos_ltda_780754',
        rf'W:\Shared With Me\Clientes\Jettax\{dtCliente_Atual}\NFS 01\NOTAS\JETTAX\elabore_repr_e_assist_tecnica_ltda_780846',
        rf'W:\Shared With Me\Clientes\Jettax\{dtCliente_Atual}\NFS 01\NOTAS\JETTAX\elias_liberato_artefatos_794347',
        rf'W:\Shared With Me\Clientes\Jettax\{dtCliente_Atual}\NFS 01\NOTAS\JETTAX\expansao_brasil_corret_de_seguros_ltd_780873',
        rf'W:\Shared With Me\Clientes\Jettax\{dtCliente_Atual}\NFS 01\NOTAS\JETTAX\fenix_assessoria_contabil_ss_ltda_epp_794348',
        rf'W:\Shared With Me\Clientes\Jettax\{dtCliente_Atual}\NFS 01\NOTAS\JETTAX\ferreira_administradora_de_bens_ltda_780825',
        rf'W:\Shared With Me\Clientes\Jettax\{dtCliente_Atual}\NFS 01\NOTAS\JETTAX\g4_brasil_ind.e_com._de_equip_elet.l_794350',
        rf'W:\Shared With Me\Clientes\Jettax\{dtCliente_Atual}\NFS 01\NOTAS\JETTAX\ga.v.a_projetos_e_solues_ltda_epp_780847',
        rf'W:\Shared With Me\Clientes\Jettax\{dtCliente_Atual}\NFS 01\NOTAS\JETTAX\gaman_consultoria_ltda_780830',
        rf'W:\Shared With Me\Clientes\Jettax\{dtCliente_Atual}\NFS 01\NOTAS\JETTAX\garage_637_inj._peas_e_serv._ltda_me_780738',
        rf'W:\Shared With Me\Clientes\Jettax\{dtCliente_Atual}\NFS 01\NOTAS\JETTAX\glk_eletronica_indst.com._ltda_epp_794352',
        rf'W:\Shared With Me\Clientes\Jettax\{dtCliente_Atual}\NFS 01\NOTAS\JETTAX\haste_centro_apoio_a_empresa_ltda-me_780782',
        rf'W:\Shared With Me\Clientes\Jettax\{dtCliente_Atual}\NFS 01\NOTAS\JETTAX\hsr_assessoria_empresarial_ltda_me_794354',
        rf'W:\Shared With Me\Clientes\Jettax\{dtCliente_Atual}\NFS 01\NOTAS\JETTAX\hyperimport_comercio_e_servicos_de_pro_780805',
        rf'W:\Shared With Me\Clientes\Jettax\{dtCliente_Atual}\NFS 01\NOTAS\JETTAX\imc_administ_de_bens_e_consult_eireli_780777',
        rf'W:\Shared With Me\Clientes\Jettax\{dtCliente_Atual}\NFS 01\NOTAS\JETTAX\ineditta_produoes_audio_e_video_ltda_780772',
        rf'W:\Shared With Me\Clientes\Jettax\{dtCliente_Atual}\NFS 01\NOTAS\JETTAX\instituto_criativas_1193377',
        rf'W:\Shared With Me\Clientes\Jettax\{dtCliente_Atual}\NFS 01\NOTAS\JETTAX\i-solutioncard_comercio_e_servicos_ltd_794357',
        rf'W:\Shared With Me\Clientes\Jettax\{dtCliente_Atual}\NFS 01\NOTAS\JETTAX\italjato_comercio_de_pecas_ltda_780820',
        rf'W:\Shared With Me\Clientes\Jettax\{dtCliente_Atual}\NFS 01\NOTAS\JETTAX\k.a.e._assessoria_administrativa_ltda_780807',
        rf'W:\Shared With Me\Clientes\Jettax\{dtCliente_Atual}\NFS 01\NOTAS\JETTAX\leandro_bezerra_da_silva_transportes_780816',
        rf'W:\Shared With Me\Clientes\Jettax\{dtCliente_Atual}\NFS 01\NOTAS\JETTAX\ls_comercio_e_solucao_especializada_em_780814',
        rf'W:\Shared With Me\Clientes\Jettax\{dtCliente_Atual}\NFS 01\NOTAS\JETTAX\luiz_carlos_mazzei_filho_mixagem_e_sonorizao_974537',
        rf'W:\Shared With Me\Clientes\Jettax\{dtCliente_Atual}\NFS 01\NOTAS\JETTAX\mar_del_mar_administradora_de_bens_ltda_1266454',
        rf'W:\Shared With Me\Clientes\Jettax\{dtCliente_Atual}\NFS 01\NOTAS\JETTAX\marco_27_ltda_epp_780730',
        rf'W:\Shared With Me\Clientes\Jettax\{dtCliente_Atual}\NFS 01\NOTAS\JETTAX\marco_aurelio_pereira_dos_santos_me_794362',
        rf'W:\Shared With Me\Clientes\Jettax\{dtCliente_Atual}\NFS 01\NOTAS\JETTAX\med_pet_shop_ltda_me_794364',
        rf'W:\Shared With Me\Clientes\Jettax\{dtCliente_Atual}\NFS 01\NOTAS\JETTAX\new_tech_sistemas_de_energia_ltda_794368',
        rf'W:\Shared With Me\Clientes\Jettax\{dtCliente_Atual}\NFS 01\NOTAS\JETTAX\nova_ouro_branco_transportes_e_locacao_794369',
        rf'W:\Shared With Me\Clientes\Jettax\{dtCliente_Atual}\NFS 01\NOTAS\JETTAX\ondo_participaes_ltda_780798',
        rf'W:\Shared With Me\Clientes\Jettax\{dtCliente_Atual}\NFS 01\NOTAS\JETTAX\ouro_branco_transp._de_agua__ltda_794371',
        rf'W:\Shared With Me\Clientes\Jettax\{dtCliente_Atual}\NFS 01\NOTAS\JETTAX\patrizia_leitao_medeiros_administrao_780788',
        rf'W:\Shared With Me\Clientes\Jettax\{dtCliente_Atual}\NFS 01\NOTAS\JETTAX\pneumoclinica_dr.adriano_g.ss_ltda_me_794373',
        rf'W:\Shared With Me\Clientes\Jettax\{dtCliente_Atual}\NFS 01\NOTAS\JETTAX\project_corp_coml_e_serv_em_imoveis_780762',
        rf'W:\Shared With Me\Clientes\Jettax\{dtCliente_Atual}\NFS 01\NOTAS\JETTAX\rafael_de_jesus_carvalho_sociedade_individual_de_advocacia_1083174',
        rf'W:\Shared With Me\Clientes\Jettax\{dtCliente_Atual}\NFS 01\NOTAS\JETTAX\roxane_lillian_bueno_roth_corresponden_780811',
        rf'W:\Shared With Me\Clientes\Jettax\{dtCliente_Atual}\NFS 01\NOTAS\JETTAX\ry_sistema_m._e._e._e_persolizado_794375',
        rf'W:\Shared With Me\Clientes\Jettax\{dtCliente_Atual}\NFS 01\NOTAS\JETTAX\safety_matriz_794380',
        rf'W:\Shared With Me\Clientes\Jettax\{dtCliente_Atual}\NFS 01\NOTAS\JETTAX\salgateria_e_pastelaria_da_divisa_ltda_780768',
        rf'W:\Shared With Me\Clientes\Jettax\{dtCliente_Atual}\NFS 01\NOTAS\JETTAX\santo_brinde_comercio_de_brindes_ltda_780817',
        rf'W:\Shared With Me\Clientes\Jettax\{dtCliente_Atual}\NFS 01\NOTAS\JETTAX\sao_luiz_administradora_de_bens_imovei_780808',
        rf'W:\Shared With Me\Clientes\Jettax\{dtCliente_Atual}\NFS 01\NOTAS\JETTAX\sao_luiz_administradora_de_bens_imovei_780808',
        rf'W:\Shared With Me\Clientes\Jettax\{dtCliente_Atual}\NFS 01\NOTAS\JETTAX\satler_fashion_company_ltda_794384',
        rf'W:\Shared With Me\Clientes\Jettax\{dtCliente_Atual}\NFS 01\NOTAS\JETTAX\sgm_consultoria_em_t.i._e_desenvolvime_780840',
        rf'W:\Shared With Me\Clientes\Jettax\{dtCliente_Atual}\NFS 01\NOTAS\JETTAX\sisalts_eventos_e_administrao_ltda_1077399',
        rf'W:\Shared With Me\Clientes\Jettax\{dtCliente_Atual}\NFS 01\NOTAS\JETTAX\sisnactech_servicos_e_acessorios_em_te_780837',
        rf'W:\Shared With Me\Clientes\Jettax\{dtCliente_Atual}\NFS 01\NOTAS\JETTAX\sizenando_fran_pont_gald_pre_serv_info_780792',
        rf'W:\Shared With Me\Clientes\Jettax\{dtCliente_Atual}\NFS 01\NOTAS\JETTAX\skybras_restaurante_exp_e_repr_ltda_780842',
        rf'W:\Shared With Me\Clientes\Jettax\{dtCliente_Atual}\NFS 01\NOTAS\JETTAX\smartverso_academy_ltda_794386',
        rf'W:\Shared With Me\Clientes\Jettax\{dtCliente_Atual}\NFS 01\NOTAS\JETTAX\smartverso_academy_ltda_794386',
        rf'W:\Shared With Me\Clientes\Jettax\{dtCliente_Atual}\NFS 01\NOTAS\JETTAX\str_comercio_de_vidros_ltda_-_epp_780761',
        rf'W:\Shared With Me\Clientes\Jettax\{dtCliente_Atual}\NFS 01\NOTAS\JETTAX\tempersol_engenharia_ltda._794388',
        rf'W:\Shared With Me\Clientes\Jettax\{dtCliente_Atual}\NFS 01\NOTAS\JETTAX\tht_filmes_ltda_1023118',
        rf'W:\Shared With Me\Clientes\Jettax\{dtCliente_Atual}\NFS 01\NOTAS\JETTAX\tmt_imoveis_ltda._780753',
        rf'W:\Shared With Me\Clientes\Jettax\{dtCliente_Atual}\NFS 01\NOTAS\JETTAX\tmt_imoveis_ltda._780753',
        rf'W:\Shared With Me\Clientes\Jettax\{dtCliente_Atual}\NFS 01\NOTAS\JETTAX\tutti_belli_comercio_de_flores_ltda_me_794391',
        rf'W:\Shared With Me\Clientes\Jettax\{dtCliente_Atual}\NFS 01\NOTAS\JETTAX\twr_filial_am_794393',
        rf'W:\Shared With Me\Clientes\Jettax\{dtCliente_Atual}\NFS 01\NOTAS\JETTAX\twr_filial_am_794393',
        rf'W:\Shared With Me\Clientes\Jettax\{dtCliente_Atual}\NFS 01\NOTAS\JETTAX\twr_matriz_794392',
        rf'W:\Shared With Me\Clientes\Jettax\{dtCliente_Atual}\NFS 01\NOTAS\JETTAX\w_w_comercio_e_distribuicao_ltda_780839',
        rf'W:\Shared With Me\Clientes\Jettax\{dtCliente_Atual}\NFS 01\NOTAS\JETTAX\yatong_sul_america_representacoes_e_co_780836',
        rf'W:\Shared With Me\Clientes\Jettax\{dtCliente_Atual}\NFS 01\NOTAS\JETTAX\yurika_comercio_de_massas_ltda_epp_780736'


    ],
    'Destino': [
        r'W:\Shared With Me\Clientes\3sixty Produtora\2024\Fiscal',
        r'W:\Shared With Me\Clientes\A&C Yabiku (filial 1) L4\2024\Fiscal',
        r'W:\Shared With Me\Clientes\A&C Matriz\2024\Fiscal',
        r'W:\Shared With Me\Clientes\Acp Equipamentos 3\2024\Fiscal',
        r'W:\Shared With Me\Clientes\ACP\2024\Fiscal',
        r'W:\Shared With Me\Clientes\Adachi\2024\Fiscal',
        r'W:\Shared With Me\Clientes\Agile\2024\Fiscal',
        r'W:\Shared With Me\Clientes\Aguaplus Poços\2024\Fiscal',
        r'W:\Shared With Me\Clientes\Aguaplus Saneamento\2024\Fiscal',
        r'W:\Shared With Me\Clientes\Andrea Oki\2024\Fiscal',
        r'W:\Shared With Me\Clientes\Netuno Escola\2024\Fiscal',
        r'W:\Shared With Me\Clientes\Iris & Gustavo\2024\Fiscal',
        r'W:\Shared With Me\Clientes\Bdm\2024\Fiscal',
        r'W:\Shared With Me\Clientes\Bruno Andre\2024\Fiscal',
        r'W:\Shared With Me\Clientes\Caio  M Azeredo\2024\Fiscal',
        r'W:\Shared With Me\Clientes\Cecere Adm\2024\Fiscal',
        r'W:\Shared With Me\Clientes\Citini Representacao\2024\Fiscal',
        r'W:\Shared With Me\Clientes\Clinica Valentim\2024\Fiscal',
        r'W:\Shared With Me\Clientes\Clinica Vet Nosso Lar\2024\Fiscal',
        r'W:\Shared With Me\Clientes\Companys Comercio\2024\Fiscal',
        r'W:\Shared With Me\Clientes\Consultorio Suguiura\2024\Fiscal',
        r'W:\Shared With Me\Clientes\D Gonçalves\2024\Fiscal',
        r'W:\Shared With Me\Clientes\Dac SS\2024\Fiscal',
        r'W:\Shared With Me\Clientes\Davi adm\2024\Fiscal',
        r'W:\Shared With Me\Clientes\Dotbuild It\2024\Fiscal',
        r'W:\Shared With Me\Clientes\Dotbuild Sistemas\2024\Fiscal',
        r'W:\Shared With Me\Clientes\Eco Terra\2024\Fiscal',
        r'W:\Shared With Me\Clientes\Elabore Representaçoes\2024\Fiscal',
        r'W:\Shared With Me\Clientes\Elias Liberato\2024\Fiscal',
        r'W:\Shared With Me\Clientes\Expansão Brasil\2024\Fiscal',
        r'W:\Shared With Me\Clientes\Fenix Assessoria\2024\Fiscal',
        r'W:\Shared With Me\Clientes\Ferreira Adm\2024\Fiscal',
        r'W:\Shared With Me\Clientes\G4 Brasil\2024\Fiscal',
        r'W:\Shared With Me\Clientes\Gava Projetos\2024\Fiscal',
        r'W:\Shared With Me\Clientes\Gaman Consultoria\2024\Fiscal',
        r'W:\Shared With Me\Clientes\Garage 637\2024\Fiscal',
        r'W:\Shared With Me\Clientes\Glk Eletronica\2024\Fiscal',
        r'W:\Shared With Me\Clientes\Haste Apoio\2024\Fiscal',
        r'W:\Shared With Me\Clientes\Hsr Assessoria\2024\Fiscal',
        r'W:\Shared With Me\Clientes\Hyperimport Comercio\2024\Fiscal',
        r'W:\Shared With Me\Clientes\Imc Administração\2024\Fiscal',
        r'W:\Shared With Me\Clientes\Ineditta Produçoes\2024\Fiscal',
        r'W:\Shared With Me\Clientes\Instituto Criativas\2024\Fiscal',
        r'W:\Shared With Me\Clientes\I Solutioncard\2024\Fiscal',
        r'W:\Shared With Me\Clientes\Italjato\2024\Fiscal',
        r'W:\Shared With Me\Clientes\K.A.E\2024\Fiscal',
        r'W:\Shared With Me\Clientes\Leandro Transportes\2024\Fiscal',
        r'W:\Shared With Me\Clientes\LS Comercio (Lar Santa)\2024\Fiscal',
        r'W:\Shared With Me\Clientes\Luiz Mazzei\2024\Fiscal',
        r'W:\Shared With Me\Clientes\Mar Del Mar\2024\Fiscal',
        r'W:\Shared With Me\Clientes\Marco 27\2024\Fiscal',
        r'W:\Shared With Me\Clientes\Marco Aurelio\2024\Fiscal',
        r'W:\Shared With Me\Clientes\Med Pet\2024\Fiscal',
        r'W:\Shared With Me\Clientes\New Tech\2024\Fiscal',
        r'W:\Shared With Me\Clientes\Nova Ouro\2024\Fiscal',
        r'W:\Shared With Me\Clientes\Ondo Participações\2024\Fiscal',
        r'W:\Shared With Me\Clientes\Ouro Branco\2024\Fiscal',
        r'W:\Shared With Me\Clientes\Patrizia Leitão (ernani imóveis)\2024\Fiscal',
        r'W:\Shared With Me\Clientes\Pneumoclinica Dr Adriano\2024\Fiscal',
        r'W:\Shared With Me\Clientes\Project Corp\2024\Fiscal',
        r'W:\Shared With Me\Clientes\Rafael Carvalho\2024\Fiscal',
        r'W:\Shared With Me\Clientes\Roxane Lillian\2024\Fiscal',
        r'W:\Shared With Me\Clientes\R&Y Sistema\2024\Fiscal',
        r'W:\Shared With Me\Clientes\Safety\2024\Fiscal',
        r'W:\Shared With Me\Clientes\Salgateria\2024\Fiscal',
        r'W:\Shared With Me\Clientes\Santo Brinde\2024\Fiscal',
        r'W:\Shared With Me\Clientes\Sao Jorge Alimentos\2024\Fiscal',
        r'W:\Shared With Me\Clientes\Sao Luiz\2024\Fiscal',
        r'W:\Shared With Me\Clientes\Satler Fashion\2024\Fiscal',
        r'W:\Shared With Me\Clientes\SGM Consultoria\2024\Fiscal',
        r'W:\Shared With Me\Clientes\Sisalts Eventos\2024\Fiscal',
        r'W:\Shared With Me\Clientes\Sisnacteh Serviços\2024\Fiscal',
        r'W:\Shared With Me\Clientes\Sizenando Fran\2024\Fiscal',
        r'W:\Shared With Me\Clientes\Skybras Exportação\2024\Fiscal',
        r'W:\Shared With Me\Clientes\Smartverso\2024\Fiscal',
        r'W:\Shared With Me\Clientes\Smartverso\2024\Fiscal',
        r'W:\Shared With Me\Clientes\Str Comércio\2024\Fiscal',
        r'W:\Shared With Me\Clientes\Tempersol Engenharia\2024\Fiscal',
        r'W:\Shared With Me\Clientes\THT Filmes\2024\Fiscal',
        r'W:\Shared With Me\Clientes\Tmt Imóveis\2024\Fiscal',
        r'W:\Shared With Me\Clientes\Tmt Imóveis\2024\Fiscal',
        r'W:\Shared With Me\Clientes\Tutti Belli\2024\Fiscal',
        r'W:\Shared With Me\Clientes\Twr filial manaus (filial 02)\2024\Fiscal',
        r'W:\Shared With Me\Clientes\Twr filial manaus (filial 02)\2024\Fiscal',
        r'W:\Shared With Me\Clientes\TWR Matriz\2024\Fiscal',
        r'W:\Shared With Me\Clientes\WW Comercio\2024\Fiscal',
        r'W:\Shared With Me\Clientes\Yatong Sul\2024\Fiscal',
        r'W:\Shared With Me\Clientes\Yurika Comércio\2024\Fiscal'
]
}

print (dtCliente_Atual)